openapi: 3.0.0
info:
  version: 0.0.4
  title: Apply API
servers:
  - url: "https://example.com/vendor-api/v1"
paths:
  "/applications/{application_id}":
    get:
      summary: Retrieve an application
      parameters:
        - $ref: "#/components/parameters/application_id"
      responses:
        "200":
          description: An application
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/Application"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"
  /applications:
    get:
      summary: Retrieve many applications. Applications are returned in the order they were changed or created.
      parameters:
        - name: since
          description: Include only applications changed or created on or since a date and time. Times should be in ISO 8601 format.
          in: query
          required: true
          schema:
            type: string
            format: date-time
        - name: order
          description: Specify how the returned applications are to be sorted. If missing, defaults to newest_first
          in: query
          schema:
            type: string
            default: newest_first
            enum:
              - newest_first
              - oldest_first
      responses:
        "200":
          description: An array of applications
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/Application"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"
  "/applications/{application_id}/offer":
    post:
      summary: Make an unconditional or conditional offer
      parameters:
        - $ref: '#/components/parameters/application_id'
      requestBody:
        description: |
          The conditions of the offer

          Providing a request body with an array of conditions is equivalent to making a **conditional** offer. For an **unconditional** offer, provide an empty request body.
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  $ref: "#/components/schemas/Offer"
      responses:
        "201":
          description: An application
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/Application"
  "/applications/{application_id}/confirm-enrolment":
    post:
      summary: Confirm candidate enrolment
      parameters:
        - $ref: '#/components/parameters/application_id'
      responses:
        "204":
          description: An application
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/Application"
  "/applications/{application_id}/confirm-conditions-met":
    post:
      summary: Confirm offer conditions are met
      parameters:
        - $ref: '#/components/parameters/application_id'
      responses:
        "204":
          description: An application
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/Application"
  "/applications/{application_id}/reject":
    post:
      summary: Reject an application
      parameters:
        - $ref: '#/components/parameters/application_id'
      requestBody:
        description: The reason for rejection
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    reason:
                      type: string
                      example: Does not meet minimum GCSE requirements
      responses:
        "201":
          description: An application
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/Application"
components:
  responses:
    NotFound:
      description: Not found
      content:
        application/json:
          schema:
            type: object
            properties:
              errors:
                type: array
                items:
                  $ref: "#/components/schemas/Error"
                example:
                  error: NotFound
                  message: Unable to find Application(s)

    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              errors:
                type: array
                items:
                  $ref: "#/components/schemas/Error"
                example:
                  error: Unauthorized
                  message: Please provide a valid authentication token
  schemas:
    Application:
      type: object
      additionalProperties: false
      required:
        - id
        - type
        - attributes
      properties:
        id:
          type: string
          description: The unique ID of this application
          maxLength: 10
          example: 11fc0d3b2f
        type:
          type: string
          enum:
            - application
          example: application
        attributes:
          $ref: "#/components/schemas/ApplicationAttributes"
    ApplicationAttributes:
      type: object
      additionalProperties: false
      properties:
        status:
          type: string
          description: The status of this application
          enum:
            - accepted
            - rejected
          example: accepted
        submitted_at:
          type: string
          format: date-time
          description: ISO 8601 date of submission, with time and timezone
          example: "2019-06-13T10:44:31Z"
        updated_at:
          type: string
          format: date-time
          description: ISO 8601 date of last change, with time and timezone
          example: "2019-06-13T10:44:31Z"
        personal_statement:
          type: string
          description: The candidate’s personal statement
          maxLength: 500
          example: "Since retiring from the Police Service in 2007..."
        candidate:
          $ref: "#/components/schemas/Candidate"
        contact_details:
          $ref: "#/components/schemas/ContactDetails"
        course:
          $ref: "#/components/schemas/Course"
        qualifications:
          type: array
          items:
            $ref: "#/components/schemas/Qualification"
        work_experiences:
          type: array
          items:
            $ref: "#/components/schemas/WorkExperience"
        references:
          type: array
          items:
            $ref: "#/components/schemas/Reference"
        offer:
          $ref: "#/components/schemas/Offer"
        withdrawal:
          $ref: "#/components/schemas/Withdrawal"
        rejection:
          $ref: "#/components/schemas/Rejection"
    Candidate:
      type: object
      additionalProperties: false
      properties:
        first_name:
          type: string
          description: The candidate’s first name
          maxLength: 60
          example: Boris
        last_name:
          type: string
          description: The candidate’s last name
          example: Brown
          maxLength: 60
        date_of_birth:
          type: string
          format: date
          description: The candidate’s date of birth
          example: "1985-02-02"
        nationality:
          type: array
          items:
            type: string
            pattern: "^[A-Z]{2}$"
            example: NL
          maxItems: 2
          description: One or more ISO 3166 country codes
        uk_residency_status:
          type: string
          description: "The candidate’s UK residency status, e.g. Citizen"
          example: UK Citizen
    ContactDetails:
      type: object
      additionalProperties: false
      properties:
        address_line1:
          type: string
          description: The candidate’s address line 1
          maxLength: 50
          example: 45
        address_line2:
          type: string
          description: The candidate’s address line 2
          maxLength: 50
          example: Dialstone Lane
        address_line3:
          type: string
          description: The candidate’s address line 3
          maxLength: 50
          example: Stockport
        address_line4:
          type: string
          description: The candidate’s address line 4
          maxLength: 50
          example: England
        postcode:
          type: string
          description: The candidate’s postcode
          maxLength: 8
          example: SK2 6AA
        country:
          type: string
          description: The candidate’s country - ISO 3166 country code
          pattern: "^[A-Z]{2}$"
          example: GB
        email:
          type: string
          description: The candidate’s email address
          maxLength: 100
          example: boris.brown@example.com
        phone_number:
          type: string
          description: The candidate’s phone number
          maxLength: 18
          example: 07944386555
    Course:
      type: object
      additionalProperties: false
      properties:
        start_date:
          type: string
          format: date
          description: The course’s start date
          example: "2020-09-10"
        provider_ucas_code:
          type: string
          description: The provider’s UCAS code
          example: 2FR
        course_ucas_code:
          type: string
          description: The course’s UCAS code
          example: 3CVK
        location_ucas_code:
          type: string
          description: The location’s UCAS code
          example: K
    Offer:
      type: object
      additionalProperties: false
      properties:
        conditions:
          type: array
          items:
            type: string
            maxLength: 255
          description: The conditions of the offer
          maxItems: 20
          example:
            - Completion of subject knowledge enhancement
            - Completion of professional skills test
    Qualification:
      type: object
      additionalProperties: false
      properties:
        qualification_type:
          type: string
          description: The qualification awarded
          example: BA
        subject:
          type: string
          description: The subject studied
          example: History and Politics
        result:
          type: string
          description: The grade awarded
          example: "2:1"
        award_year:
          type: string
          description: The year the award was made
          example: "1992"
        place_of_study:
          type: string
          description: The place of study
          example: University of Huddersfield
        awarding_body_name:
          type: string
          description: "Optional. The awarding body’s name, e.g. AQA"
        awarding_body_country:
          type: string
          description: The awarding body’s country as an ISO 3166 country code
          example: GB
        equivalency_details:
          type: string
          description: Optional. Details of equivalency, if this qualification was awarded overseas
    Reference:
      type: object
      additionalProperties: false
      properties:
        reference_type:
          type: string
          description: The type of the reference
          enum:
            - academic
            - professional
            - school_senior_leadership
            - character
          example: school_senior_leadership
        reason_for_character_reference:
          type: string
          description: "If this is a character reference, this field will contain the reason the candidate gave for not providing one of the other types"
        email:
          type: string
          description: The referee’s email
          example: julia@example.com
        name:
          type: string
          description: The referee’s name
          example: Julia Wild
        relationship:
          type: string
          description: The referee’s relationship to the candidate
          example: Julia was my mentor at Cheadle Hulme High
        content:
          type: string
          description: "Optional. The reference content provided by the referee, once it is available"
          example: Boris is committed to the profession of teaching...
    Rejection:
      type: object
      additionalProperties: false
      properties:
        reason:
          type: string
          description: The reason for rejection
          example: Does not meet minimum GCSE requirements
        date:
          type: string
          format: date-time
          description: The date on which the rejection was issued
          example: "2019-09-18T15:33:49.216Z"
    Withdrawal:
      type: object
      additionalProperties: false
      properties:
        reason:
          type: string
          description: Optional. The candidate’s reason for withdrawing
          example: Candidate is unwell
        date:
          type: string
          format: date-time
          description: The date on which the withdrawal was received
          example: "2019-09-18T15:33:49.216Z"
    WorkExperience:
      type: object
      additionalProperties: false
      properties:
        organisation_name:
          type: string
          description: The name of the employer (company or individual)
          example: Cheadle Hulme High School
        start_date:
          type: string
          format: date
          description: The date employment began
          example: "2020-09-10"
        end_date:
          type: string
          format: date
          description: "The date employment finished, if appropriate"
          example: "2019-04-01"
        role:
          type: string
          description: The position held by the candidate
          example: Whole School Literacy Specialist
        description:
          type: string
          description: A brief written description of the work involved
          example: "I lead, develop and enhance the literacy teaching practice of others..."
    Error:
      type: object
      additionalProperties: false
      properties:
        error:
          type: string
          description: Name of the current error
          example: "Unauthorized"
        message:
          type: string
          description: Description of the current error
          example: Please provide a valid authentication token
      required:
        - error
        - message
  parameters:
    application_id:
      name: application_id
      in: path
      required: true
      description: The unique ID of this application
      schema:
        type: string
        maxLength: 10
